/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Address
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-31T17:38:54.800+01:00")
public class Address {
  @JsonProperty("adrCodPst")
  private String adrCodPst = null;

  @JsonProperty("adrLibAdr001")
  private String adrLibAdr001 = null;

  @JsonProperty("adrLibAdr002")
  private String adrLibAdr002 = null;

  @JsonProperty("adrLibAdr003")
  private String adrLibAdr003 = null;

  @JsonProperty("adrLibVil")
  private String adrLibVil = null;

  @JsonProperty("adrNumPay")
  private String adrNumPay = null;

  public Address adrCodPst(String adrCodPst) {
    this.adrCodPst = adrCodPst;
    return this;
  }

   /**
   * Get adrCodPst
   * @return adrCodPst
  **/
  @ApiModelProperty(value = "")
  public String getAdrCodPst() {
    return adrCodPst;
  }

  public void setAdrCodPst(String adrCodPst) {
    this.adrCodPst = adrCodPst;
  }

  public Address adrLibAdr001(String adrLibAdr001) {
    this.adrLibAdr001 = adrLibAdr001;
    return this;
  }

   /**
   * Get adrLibAdr001
   * @return adrLibAdr001
  **/
  @ApiModelProperty(value = "")
  public String getAdrLibAdr001() {
    return adrLibAdr001;
  }

  public void setAdrLibAdr001(String adrLibAdr001) {
    this.adrLibAdr001 = adrLibAdr001;
  }

  public Address adrLibAdr002(String adrLibAdr002) {
    this.adrLibAdr002 = adrLibAdr002;
    return this;
  }

   /**
   * Get adrLibAdr002
   * @return adrLibAdr002
  **/
  @ApiModelProperty(value = "")
  public String getAdrLibAdr002() {
    return adrLibAdr002;
  }

  public void setAdrLibAdr002(String adrLibAdr002) {
    this.adrLibAdr002 = adrLibAdr002;
  }

  public Address adrLibAdr003(String adrLibAdr003) {
    this.adrLibAdr003 = adrLibAdr003;
    return this;
  }

   /**
   * Get adrLibAdr003
   * @return adrLibAdr003
  **/
  @ApiModelProperty(value = "")
  public String getAdrLibAdr003() {
    return adrLibAdr003;
  }

  public void setAdrLibAdr003(String adrLibAdr003) {
    this.adrLibAdr003 = adrLibAdr003;
  }

  public Address adrLibVil(String adrLibVil) {
    this.adrLibVil = adrLibVil;
    return this;
  }

   /**
   * Get adrLibVil
   * @return adrLibVil
  **/
  @ApiModelProperty(value = "")
  public String getAdrLibVil() {
    return adrLibVil;
  }

  public void setAdrLibVil(String adrLibVil) {
    this.adrLibVil = adrLibVil;
  }

  public Address adrNumPay(String adrNumPay) {
    this.adrNumPay = adrNumPay;
    return this;
  }

   /**
   * Get adrNumPay
   * @return adrNumPay
  **/
  @ApiModelProperty(value = "")
  public String getAdrNumPay() {
    return adrNumPay;
  }

  public void setAdrNumPay(String adrNumPay) {
    this.adrNumPay = adrNumPay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.adrCodPst, address.adrCodPst) &&
        Objects.equals(this.adrLibAdr001, address.adrLibAdr001) &&
        Objects.equals(this.adrLibAdr002, address.adrLibAdr002) &&
        Objects.equals(this.adrLibAdr003, address.adrLibAdr003) &&
        Objects.equals(this.adrLibVil, address.adrLibVil) &&
        Objects.equals(this.adrNumPay, address.adrNumPay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adrCodPst, adrLibAdr001, adrLibAdr002, adrLibAdr003, adrLibVil, adrNumPay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    adrCodPst: ").append(toIndentedString(adrCodPst)).append("\n");
    sb.append("    adrLibAdr001: ").append(toIndentedString(adrLibAdr001)).append("\n");
    sb.append("    adrLibAdr002: ").append(toIndentedString(adrLibAdr002)).append("\n");
    sb.append("    adrLibAdr003: ").append(toIndentedString(adrLibAdr003)).append("\n");
    sb.append("    adrLibVil: ").append(toIndentedString(adrLibVil)).append("\n");
    sb.append("    adrNumPay: ").append(toIndentedString(adrNumPay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

