/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RestFilter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Facet
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-31T17:38:54.800+01:00")
public class Facet {
  @JsonProperty("filtersByPropertyPath")
  private Map<String, RestFilter> filtersByPropertyPath = null;

  @JsonProperty("propertyPaths")
  private List<String> propertyPaths = null;

  public Facet filtersByPropertyPath(Map<String, RestFilter> filtersByPropertyPath) {
    this.filtersByPropertyPath = filtersByPropertyPath;
    return this;
  }

  public Facet putFiltersByPropertyPathItem(String key, RestFilter filtersByPropertyPathItem) {
    if (this.filtersByPropertyPath == null) {
      this.filtersByPropertyPath = new HashMap<String, RestFilter>();
    }
    this.filtersByPropertyPath.put(key, filtersByPropertyPathItem);
    return this;
  }

   /**
   * Get filtersByPropertyPath
   * @return filtersByPropertyPath
  **/
  @ApiModelProperty(value = "")
  public Map<String, RestFilter> getFiltersByPropertyPath() {
    return filtersByPropertyPath;
  }

  public void setFiltersByPropertyPath(Map<String, RestFilter> filtersByPropertyPath) {
    this.filtersByPropertyPath = filtersByPropertyPath;
  }

  public Facet propertyPaths(List<String> propertyPaths) {
    this.propertyPaths = propertyPaths;
    return this;
  }

  public Facet addPropertyPathsItem(String propertyPathsItem) {
    if (this.propertyPaths == null) {
      this.propertyPaths = new ArrayList<String>();
    }
    this.propertyPaths.add(propertyPathsItem);
    return this;
  }

   /**
   * Get propertyPaths
   * @return propertyPaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getPropertyPaths() {
    return propertyPaths;
  }

  public void setPropertyPaths(List<String> propertyPaths) {
    this.propertyPaths = propertyPaths;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Facet facet = (Facet) o;
    return Objects.equals(this.filtersByPropertyPath, facet.filtersByPropertyPath) &&
        Objects.equals(this.propertyPaths, facet.propertyPaths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filtersByPropertyPath, propertyPaths);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Facet {\n");
    
    sb.append("    filtersByPropertyPath: ").append(toIndentedString(filtersByPropertyPath)).append("\n");
    sb.append("    propertyPaths: ").append(toIndentedString(propertyPaths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

