/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Facet;
import io.swagger.client.model.ProductLineItemDto;
import java.util.ArrayList;
import java.util.List;

/**
 * PaginableRestResultProductLineItemDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-31T17:38:54.800+01:00")
public class PaginableRestResultProductLineItemDto {
  @JsonProperty("data")
  private List<ProductLineItemDto> data = null;

  @JsonProperty("facet")
  private Facet facet = null;

  @JsonProperty("recordsFiltered")
  private Long recordsFiltered = null;

  @JsonProperty("recordsTotal")
  private Long recordsTotal = null;

  public PaginableRestResultProductLineItemDto data(List<ProductLineItemDto> data) {
    this.data = data;
    return this;
  }

  public PaginableRestResultProductLineItemDto addDataItem(ProductLineItemDto dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<ProductLineItemDto>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<ProductLineItemDto> getData() {
    return data;
  }

  public void setData(List<ProductLineItemDto> data) {
    this.data = data;
  }

  public PaginableRestResultProductLineItemDto facet(Facet facet) {
    this.facet = facet;
    return this;
  }

   /**
   * Get facet
   * @return facet
  **/
  @ApiModelProperty(value = "")
  public Facet getFacet() {
    return facet;
  }

  public void setFacet(Facet facet) {
    this.facet = facet;
  }

  public PaginableRestResultProductLineItemDto recordsFiltered(Long recordsFiltered) {
    this.recordsFiltered = recordsFiltered;
    return this;
  }

   /**
   * Get recordsFiltered
   * @return recordsFiltered
  **/
  @ApiModelProperty(value = "")
  public Long getRecordsFiltered() {
    return recordsFiltered;
  }

  public void setRecordsFiltered(Long recordsFiltered) {
    this.recordsFiltered = recordsFiltered;
  }

  public PaginableRestResultProductLineItemDto recordsTotal(Long recordsTotal) {
    this.recordsTotal = recordsTotal;
    return this;
  }

   /**
   * Get recordsTotal
   * @return recordsTotal
  **/
  @ApiModelProperty(value = "")
  public Long getRecordsTotal() {
    return recordsTotal;
  }

  public void setRecordsTotal(Long recordsTotal) {
    this.recordsTotal = recordsTotal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginableRestResultProductLineItemDto paginableRestResultProductLineItemDto = (PaginableRestResultProductLineItemDto) o;
    return Objects.equals(this.data, paginableRestResultProductLineItemDto.data) &&
        Objects.equals(this.facet, paginableRestResultProductLineItemDto.facet) &&
        Objects.equals(this.recordsFiltered, paginableRestResultProductLineItemDto.recordsFiltered) &&
        Objects.equals(this.recordsTotal, paginableRestResultProductLineItemDto.recordsTotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, facet, recordsFiltered, recordsTotal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginableRestResultProductLineItemDto {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    facet: ").append(toIndentedString(facet)).append("\n");
    sb.append("    recordsFiltered: ").append(toIndentedString(recordsFiltered)).append("\n");
    sb.append("    recordsTotal: ").append(toIndentedString(recordsTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

