/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Product
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-31T17:38:54.800+01:00")
public class Product {
  @JsonProperty("descriptionArt")
  private String descriptionArt = null;

  @JsonProperty("numArtFou")
  private String numArtFou = null;

  @JsonProperty("numArtInt")
  private String numArtInt = null;

  public Product descriptionArt(String descriptionArt) {
    this.descriptionArt = descriptionArt;
    return this;
  }

   /**
   * Get descriptionArt
   * @return descriptionArt
  **/
  @ApiModelProperty(value = "")
  public String getDescriptionArt() {
    return descriptionArt;
  }

  public void setDescriptionArt(String descriptionArt) {
    this.descriptionArt = descriptionArt;
  }

  public Product numArtFou(String numArtFou) {
    this.numArtFou = numArtFou;
    return this;
  }

   /**
   * Get numArtFou
   * @return numArtFou
  **/
  @ApiModelProperty(value = "")
  public String getNumArtFou() {
    return numArtFou;
  }

  public void setNumArtFou(String numArtFou) {
    this.numArtFou = numArtFou;
  }

  public Product numArtInt(String numArtInt) {
    this.numArtInt = numArtInt;
    return this;
  }

   /**
   * Get numArtInt
   * @return numArtInt
  **/
  @ApiModelProperty(value = "")
  public String getNumArtInt() {
    return numArtInt;
  }

  public void setNumArtInt(String numArtInt) {
    this.numArtInt = numArtInt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.descriptionArt, product.descriptionArt) &&
        Objects.equals(this.numArtFou, product.numArtFou) &&
        Objects.equals(this.numArtInt, product.numArtInt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descriptionArt, numArtFou, numArtInt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    descriptionArt: ").append(toIndentedString(descriptionArt)).append("\n");
    sb.append("    numArtFou: ").append(toIndentedString(numArtFou)).append("\n");
    sb.append("    numArtInt: ").append(toIndentedString(numArtInt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

