/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.MissionDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MissionControllerApi
 */
@Ignore
public class MissionControllerApiTest {

    private final MissionControllerApi api = new MissionControllerApi();

    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMissionUsingDELETETest() {
        String buCode = null;
        String missionId = null;
        api.deleteMissionUsingDELETE(buCode, missionId);

        // TODO: test validations
    }
    
    /**
     * patch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchMissionUsingPATCHTest() {
        String buCode = null;
        MissionDto mission = null;
        String missionId = null;
        api.patchMissionUsingPATCH(buCode, mission, missionId);

        // TODO: test validations
    }
    
    /**
     * post
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postMissionUsingPOSTTest() {
        String buCode = null;
        MissionDto missionDto = null;
        api.postMissionUsingPOST(buCode, missionDto);

        // TODO: test validations
    }
    
    /**
     * put
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putMissionUsingPUTTest() {
        String buCode = null;
        MissionDto mission = null;
        String missionId = null;
        api.putMissionUsingPUT(buCode, mission, missionId);

        // TODO: test validations
    }
    
}
