/*
 * heros API
 * heros
 *
 * OpenAPI spec version: heros
 * Contact: email@a.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.PaginableRestResultMissionDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MissionByHeroControllerApi
 */
@Ignore
public class MissionByHeroControllerApiTest {

    private final MissionByHeroControllerApi api = new MissionByHeroControllerApi();

    
    /**
     * Retrieves a list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMissionPaginatedUsingGETTest() {
        String buCode = null;
        String hero = null;
        String filter = null;
        Integer limit = null;
        Integer offset = null;
        String search = null;
        List<String> sort = null;
        PaginableRestResultMissionDto response = api.listMissionPaginatedUsingGET(buCode, hero, filter, limit, offset, search, sort);

        // TODO: test validations
    }
    
}
